In [ ]:
import pandas as pd
import numpy as np

df = pd.read_excel("../../data/raw/flights.xlsx")

df.head()
df.shape
df.columns.tolist()
df.info()
df.isnull().sum()
df.duplicated().sum()
df.head()
print("Airlines:")
print(df["Airline"].value_counts())

print("\nSources:")
print(df["Source"].value_counts())

print("\nDestinations:")
print(df["Destination"].value_counts())

print("\nStops:")
print(df["Total_Stops"].value_counts())

print("\nAdditional Info:")
print(df["Additional_Info"].value_counts())

df["Price"].describe()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB
Airlines:
Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

Sources:
Source
Delhi       4537
Kolkata     2871
Banglore    2197
Mumbai       697
Chennai      381
Name: count, dtype: int64

Destinations:
Destination
Cochin       4537
Banglore     2871
Delhi        1265
New Delhi     932
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

Stops:
Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

Additional Info:
Additional_Info
No info                         8345
In-flight meal not included     1982
No check-in baggage included     320
1 Long layover                    19
Change airports                    7
Business class                     4
No Info                            3
1 Short layover                    1
Red-eye flight                     1
2 Long layover                     1
Name: count, dtype: int64

count    10683.000000
mean      9087.064121
std       4611.359167
min       1759.000000
25%       5277.000000
50%       8372.000000
75%      12373.000000
max      79512.000000
Name: Price, dtype: float64

In [11]:
df[["Route", "Total_Stops"]].head(20)

                    Route Total_Stops
0               BLR → DEL    non-stop
1   CCU → IXR → BBI → BLR     2 stops
2   DEL → LKO → BOM → COK     2 stops
3         CCU → NAG → BLR      1 stop
4         BLR → NAG → DEL      1 stop
5               CCU → BLR    non-stop
6         BLR → BOM → DEL      1 stop
7         BLR → BOM → DEL      1 stop
8         BLR → BOM → DEL      1 stop
9         DEL → BOM → COK      1 stop
10        DEL → BLR → COK      1 stop
11              CCU → BLR    non-stop
12              MAA → CCU    non-stop
13        CCU → BOM → BLR      1 stop
14              CCU → BLR    non-stop
15  DEL → AMD → BOM → COK     2 stops
16        DEL → PNQ → COK      1 stop
17        DEL → BOM → COK      1 stop
18  DEL → CCU → BOM → COK     2 stops
19        DEL → BOM → COK      1 stop

In [12]:
df.shape

(10683, 11)

In [13]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(220)

In [15]:
df["Airline"].value_counts()

Airline
Jet Airways                          3849
IndiGo                               2053
Air India                            1752
Multiple carriers                    1196
SpiceJet                              818
Vistara                               479
Air Asia                              319
GoAir                                 194
Multiple carriers Premium economy      13
Jet Airways Business                    6
Vistara Premium economy                 3
Trujet                                  1
Name: count, dtype: int64

In [16]:
df["Total_Stops"].value_counts()

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
4 stops        1
Name: count, dtype: int64

In [17]:
df["Additional_Info"].value_counts()

Additional_Info
No info                         8345
In-flight meal not included     1982
No check-in baggage included     320
1 Long layover                    19
Change airports                    7
Business class                     4
No Info                            3
1 Short layover                    1
Red-eye flight                     1
2 Long layover                     1
Name: count, dtype: int64

In [18]:
df["Price"].describe()

count    10683.000000
mean      9087.064121
std       4611.359167
min       1759.000000
25%       5277.000000
50%       8372.000000
75%      12373.000000
max      79512.000000
Name: Price, dtype: float64

In [19]:
df[["Route", "Total_Stops"]].head(20)

                    Route Total_Stops
0               BLR → DEL    non-stop
1   CCU → IXR → BBI → BLR     2 stops
2   DEL → LKO → BOM → COK     2 stops
3         CCU → NAG → BLR      1 stop
4         BLR → NAG → DEL      1 stop
5               CCU → BLR    non-stop
6         BLR → BOM → DEL      1 stop
7         BLR → BOM → DEL      1 stop
8         BLR → BOM → DEL      1 stop
9         DEL → BOM → COK      1 stop
10        DEL → BLR → COK      1 stop
11              CCU → BLR    non-stop
12              MAA → CCU    non-stop
13        CCU → BOM → BLR      1 stop
14              CCU → BLR    non-stop
15  DEL → AMD → BOM → COK     2 stops
16        DEL → PNQ → COK      1 stop
17        DEL → BOM → COK      1 stop
18  DEL → CCU → BOM → COK     2 stops
19        DEL → BOM → COK      1 stop

In [20]:
df[df["Route"].isna() | df["Additional_Info"].isna()]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
9039,Air India,6/05/2019,Delhi,Cochin,NaN,09:45,09:25 07 May,23h 40m,NaN,No info,7480

In [21]:
df[df.duplicated(keep=False)].sort_values(
    by=["Airline", "Source", "Destination"]
).head(20)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
572,Air India,03/03/2019,Banglore,New Delhi,BLR → DEL,21:10,23:55,2h 45m,non-stop,No info,7591
5222,Air India,12/03/2019,Banglore,New Delhi,BLR → BOM → NAG → DEL,08:50,10:15 13 Mar,25h 25m,2 stops,No info,12778
6321,Air India,01/03/2019,Banglore,New Delhi,BLR → BOM → AMD → DEL,08:50,23:55 02 Mar,39h 5m,2 stops,No info,17135
8168,Air India,03/03/2019,Banglore,New Delhi,BLR → DEL,21:10,23:55,2h 45m,non-stop,No info,7591
9848,Air India,01/03/2019,Banglore,New Delhi,BLR → BOM → AMD → DEL,08:50,23:55 02 Mar,39h 5m,2 stops,No info,17135
9942,Air India,12/03/2019,Banglore,New Delhi,BLR → BOM → NAG → DEL,08:50,10:15 13 Mar,25h 25m,2 stops,No info,12778
137,Air India,27/06/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 28 Jun,21h 15m,2 stops,No info,10441
251,Air India,1/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,19:45,19:15 02 Jun,23h 30m,2 stops,No info,10651
406,Air India,21/05/2019,Delhi,Cochin,DEL → BHO → BOM → COK,05:55,07:40 22 May,25h 45m,2 stops,No info,11911
410,Air India,18/05/2019,Delhi,Cochin,DEL → HYD → BOM → COK,17:15,19:15 19 May,26h,2 stops,No info,12392
455,Air India,18/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 19 May,21h 15m,2 stops,No info,10441
646,Air India,27/03/2019,Delhi,Cochin,DEL → HYD → BOM → COK,21:30,19:15 28 Mar,21h 45m,2 stops,No info,8665
672,Air India,21/03/2019,Delhi,Cochin,DEL → AMD → BOM → COK,19:45,19:15 22 Mar,23h 30m,2 stops,No info,8236
910,Air India,21/05/2019,Delhi,Cochin,DEL → HYD → BOM → COK,17:15,19:15 22 May,26h,2 stops,No info,11972
969,Air India,6/03/2019,Delhi,Cochin,DEL → HYD → BOM → COK,07:05,19:15 07 Mar,36h 10m,2 stops,No info,11552
1025,Air India,21/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 22 May,21h 15m,2 stops,No info,10231
1042,Air India,21/03/2019,Delhi,Cochin,DEL → HYD → BOM → COK,17:15,19:15 22 Mar,26h,2 stops,No info,8245
1061,Air India,21/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 22 May,21h 15m,2 stops,No info,10231
1069,Air India,1/06/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 02 Jun,21h 15m,2 stops,No info,10441
1348,Air India,18/05/2019,Delhi,Cochin,DEL → HYD → BOM → COK,17:15,19:15 19 May,26h,2 stops,No info,12392

In [22]:
df[df["Route"].isna() | df["Additional_Info"].isna()]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
9039,Air India,6/05/2019,Delhi,Cochin,NaN,09:45,09:25 07 May,23h 40m,NaN,No info,7480

In [23]:
df[df.duplicated(keep=False)].sort_values(
    by=["Airline", "Source", "Destination"]
).head(20)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
572,Air India,03/03/2019,Banglore,New Delhi,BLR → DEL,21:10,23:55,2h 45m,non-stop,No info,7591
5222,Air India,12/03/2019,Banglore,New Delhi,BLR → BOM → NAG → DEL,08:50,10:15 13 Mar,25h 25m,2 stops,No info,12778
6321,Air India,01/03/2019,Banglore,New Delhi,BLR → BOM → AMD → DEL,08:50,23:55 02 Mar,39h 5m,2 stops,No info,17135
8168,Air India,03/03/2019,Banglore,New Delhi,BLR → DEL,21:10,23:55,2h 45m,non-stop,No info,7591
9848,Air India,01/03/2019,Banglore,New Delhi,BLR → BOM → AMD → DEL,08:50,23:55 02 Mar,39h 5m,2 stops,No info,17135
9942,Air India,12/03/2019,Banglore,New Delhi,BLR → BOM → NAG → DEL,08:50,10:15 13 Mar,25h 25m,2 stops,No info,12778
137,Air India,27/06/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 28 Jun,21h 15m,2 stops,No info,10441
251,Air India,1/06/2019,Delhi,Cochin,DEL → AMD → BOM → COK,19:45,19:15 02 Jun,23h 30m,2 stops,No info,10651
406,Air India,21/05/2019,Delhi,Cochin,DEL → BHO → BOM → COK,05:55,07:40 22 May,25h 45m,2 stops,No info,11911
410,Air India,18/05/2019,Delhi,Cochin,DEL → HYD → BOM → COK,17:15,19:15 19 May,26h,2 stops,No info,12392
455,Air India,18/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 19 May,21h 15m,2 stops,No info,10441
646,Air India,27/03/2019,Delhi,Cochin,DEL → HYD → BOM → COK,21:30,19:15 28 Mar,21h 45m,2 stops,No info,8665
672,Air India,21/03/2019,Delhi,Cochin,DEL → AMD → BOM → COK,19:45,19:15 22 Mar,23h 30m,2 stops,No info,8236
910,Air India,21/05/2019,Delhi,Cochin,DEL → HYD → BOM → COK,17:15,19:15 22 May,26h,2 stops,No info,11972
969,Air India,6/03/2019,Delhi,Cochin,DEL → HYD → BOM → COK,07:05,19:15 07 Mar,36h 10m,2 stops,No info,11552
1025,Air India,21/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 22 May,21h 15m,2 stops,No info,10231
1042,Air India,21/03/2019,Delhi,Cochin,DEL → HYD → BOM → COK,17:15,19:15 22 Mar,26h,2 stops,No info,8245
1061,Air India,21/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 22 May,21h 15m,2 stops,No info,10231
1069,Air India,1/06/2019,Delhi,Cochin,DEL → GOI → BOM → COK,22:00,19:15 02 Jun,21h 15m,2 stops,No info,10441
1348,Air India,18/05/2019,Delhi,Cochin,DEL → HYD → BOM → COK,17:15,19:15 19 May,26h,2 stops,No info,12392

In [24]:
df["Date_of_Journey"].min(), df["Date_of_Journey"].max()

('01/03/2019', '9/06/2019')

In [25]:
df.nlargest(20, "Price")[
    ["Airline", "Source", "Destination", "Route", "Total_Stops", "Price"]
]

,Airline,Source,Destination,Route,Total_Stops,Price
2924,Jet Airways Business,Banglore,New Delhi,BLR → BOM → DEL,1 stop,79512
5372,Jet Airways Business,Banglore,New Delhi,BLR → BOM → DEL,1 stop,62427
10364,Jet Airways Business,Banglore,New Delhi,BLR → MAA → DEL,1 stop,57209
1478,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,1 stop,54826
2618,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,1 stop,54826
5439,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,1 stop,54826
9715,Jet Airways Business,Delhi,Cochin,DEL → ATQ → BOM → COK,2 stops,52285
657,Jet Airways Business,Banglore,New Delhi,BLR → BOM → DEL,1 stop,52229
7351,Jet Airways Business,Delhi,Cochin,DEL → ATQ → BOM → COK,2 stops,46490
396,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,1 stop,36983
2099,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,1 stop,36235
5719,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,1 stop,36235
2693,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,1 stop,35185
8598,Multiple carriers,Delhi,Cochin,DEL → IDR → BOM → COK,2 stops,34608
7617,Multiple carriers,Delhi,Cochin,DEL → IDR → BOM → COK,2 stops,34503
6991,Multiple carriers,Delhi,Cochin,DEL → BOM → COK,1 stop,34273
10052,Air India,Kolkata,Banglore,CCU → BLR,non-stop,31945
3700,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,1 stop,31825
5013,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,1 stop,31825
5662,Jet Airways,Banglore,New Delhi,BLR → BOM → DEL,1 stop,31825

In [26]:
df[df["Total_Stops"].isna()]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
9039,Air India,6/05/2019,Delhi,Cochin,NaN,09:45,09:25 07 May,23h 40m,NaN,No info,7480